apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    access: browser
    url: http://jaeger-query:16686
    editable: true
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
