{
 "title": "latencies",
 "tags": [
  "percentiles",
  "qunatiles",
  "latencies",
  "rates"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "nginx request rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "request rate total"
    },
    {
     "expr": "rate(nginx_connections_accepted[1m])",
     "legendFormat": "… accepted"
    },
    {
     "expr": "rate(nginx_connections_handled[1m])",
     "legendFormat": "… handled"
    }
   ]
  },
  {
   "title": "frontend request rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(http_server_requests_count{job=\"frontends\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "frontend request duration",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_ms_bucket{http_route=\"/\", job=\"frontends\"}[5m])) by (le))",
     "legendFormat": "99.0"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_server_request_duration_ms_bucket{http_route=\"/\", job=\"frontends\"}[5m])) by (le))",
     "legendFormat": "99.9"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(http_server_request_duration_ms_bucket{http_route=\"/\", job=\"frontends\"}[5m])) by (le))",
     "legendFormat": "99.99"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(http_server_request_duration_ms_bucket{http_route=\"/\", job=\"frontends\"}[5m])) by (le))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "backend request rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(http_server_requests_count{job=\"backends\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "backend request duration",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_ms_bucket{http_route=\"/\", job=\"backends\"}[5m])) by (le)) * 1000",
     "legendFormat": "99.0"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_server_request_duration_ms_bucket{http_route=\"/\", job=\"backends\"}[5m])) by (le)) * 1000",
     "legendFormat": "99.9"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(http_server_request_duration_ms_bucket{http_route=\"/\", job=\"backends\"}[5m])) by (le)) * 1000",
     "legendFormat": "99.99"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(http_server_request_duration_ms_bucket{http_route=\"/\", job=\"backends\"}[5m])) by (le)) * 1000",
     "legendFormat": "max"
    }
   ]
  }
 ]
}