{
 "title": "p99s",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "nginx request rate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "request rate"
    }
   ]
  },
  {
   "title": "frontend p99 request duration",
   "type": "graph",
   "gridPos": { "h": 19, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{http_route=\"/\", job=\"frontends\"}[1m])) by (le))",
     "legendFormat": "frontend"
    }
   ]
  },
  {
   "title": "frontend request rates",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(http_server_requests_count{job=\"frontends\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "backend percentiles",
   "type": "graph",
   "gridPos": { "h": 17, "w": 11, "x": 13, "y": 19 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_ms_bucket{http_route=\"/\", job=\"backends\"}[1m])) by (le)) * 1000",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_ms_bucket{http_route=\"/\", job=\"backends\"}[1m])) by (le)) * 1000",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_ms_bucket{http_route=\"/\", job=\"backends\"}[1m])) by (le)) * 1000",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_request_duration_ms_bucket{http_route=\"/\", job=\"backends\"}[1m])) by (le)) * 1000",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "backend request rates",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(http_server_requests_count{job=\"backends\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}