global:
  scrape_interval: 10s
  scrape_timeout: 5s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: self
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'

  - job_name: nginx
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'nginx-prom:9113'

  - job_name: frontends
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'frontend01:4000'
          - 'frontend02:4000'
          - 'frontend03:4000'

  - job_name: frontend_backups
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'frontendbackup01:4000'
          - 'frontendbackup02:4000'

  - job_name: backends
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'backend01:3000'
          - 'backend02:3000'
          - 'backend03:3000'
